// Generated by scripts/import-old-site-lots.mjs from https://kronbergveiculos.github.io/LEIL-O/.
// Re-run the script after changing the old-site import rules.

export const importedOldSiteLots = [
  {
    "id": "old-site-lote-1001",
    "slug": "honda-biz-110i-2022-1001",
    "title": "Honda Biz 110i 2022",
    "subtitle": "Lote #1001 importado do site antigo com imagens locais e referência fixa.",
    "referenceCode": "Lote #1001",
    "eventId": "event-motos-maquinas",
    "categoryId": "category-motocicletas",
    "segmentLabel": "Motocicleta",
    "location": {
      "city": "São Paulo",
      "state": "SP",
      "display": "São Paulo/SP"
    },
    "statusKey": "sob-consulta",
    "statusLabel": "Sob consulta",
    "shortDescription": "Moto em bom estado, liga e dá partida normalmente. Confirme edital, disponibilidade, documentação, pagamento e retirada com a equipe antes de avançar.",
    "longDescription": [
      "Honda Biz 110i 2022/2022",
      "Moto em bom estado, liga e dá partida normalmente.",
      "O lance inicial do site antigo foi usado como referência fixa do lote. O lance atual histórico foi mantido apenas como observação de origem, sem virar pré-lance no sistema atual."
    ],
    "gallery": [
      {
        "id": "media-honda-biz-110i-2022-1001-01",
        "url": "/media/lotes/importados/honda-biz-110i-2022-1001/01-biz1.png",
        "alt": "Imagem 1 do lote honda-biz-110i-2022-1001",
        "kind": "image"
      }
    ],
    "documentIds": [],
    "faqIds": [],
    "technicalMetadata": {
      "yearModel": "2022",
      "usageMetric": "73.272 km",
      "fuel": "Gasolina"
    },
    "observations": {
      "sourceNote": "Importado do site antigo Kron Leilões em https://kronbergveiculos.github.io/LEIL-O/.",
      "commercialDisclaimer": "Dados, valores, disponibilidade, edital, comissão, pagamento, visitação e retirada devem ser confirmados com a equipe antes de qualquer decisão.",
      "operationalNotes": [
        "Combustível: Gasolina",
        "Quilometragem: 73.272 km",
        "IPVA: Pago",
        "Chaves: Com chave",
        "Placa: J*****7",
        "Lance inicial importado: R$ 1.100,00.",
        "Lance atual histórico no site antigo: R$ 1.110,00.",
        "Lance mínimo informado no site antigo: R$ 1.000,00."
      ]
    },
    "highlightBullets": [
      "Imagens baixadas do site antigo e servidas localmente pelo projeto.",
      "Referência fixa importada do lance inicial: R$ 1.100,00.",
      "Condições oficiais seguem dependentes de edital e atendimento."
    ],
    "ctaIds": [],
    "tags": [
      "moto",
      "mobilidade",
      "importado-site-antigo"
    ],
    "seo": {
      "title": "Honda Biz 110i 2022",
      "description": "Lote #1001 importado do site antigo com imagens locais e referência fixa.",
      "canonicalPath": "/lotes/honda-biz-110i-2022-1001",
      "keywords": [
        "moto",
        "mobilidade",
        "importado-site-antigo"
      ],
      "ogImage": "/media/lotes/importados/honda-biz-110i-2022-1001/01-biz1.png"
    }
  },
  {
    "id": "old-site-lote-1223",
    "slug": "t-cross-highline-1-4-2021-1223",
    "title": "T-cross Highline 1.4 2021",
    "subtitle": "Lote #1223 importado do site antigo com imagens locais e referência fixa.",
    "referenceCode": "Lote #1223",
    "eventId": "event-veiculos-premium",
    "categoryId": "category-veiculos-leves",
    "segmentLabel": "Veículo leve",
    "location": {
      "city": "Curitiba",
      "state": "PR",
      "display": "Curitiba/PR"
    },
    "statusKey": "sob-consulta",
    "statusLabel": "Sob consulta",
    "shortDescription": "Veículo semi-novo, motor ok, documento em mãos. Confirme edital, disponibilidade, documentação, pagamento e retirada com a equipe antes de avançar.",
    "longDescription": [
      "Volkswagen Highline 1.4 TSI Flex",
      "Veículo semi-novo, motor ok, documento em mãos.",
      "O lance inicial do site antigo foi usado como referência fixa do lote. O lance atual histórico foi mantido apenas como observação de origem, sem virar pré-lance no sistema atual."
    ],
    "gallery": [
      {
        "id": "media-t-cross-highline-1-4-2021-1223-01",
        "url": "/media/lotes/importados/t-cross-highline-1-4-2021-1223/01-tcross.webp",
        "alt": "Imagem 1 do lote t-cross-highline-1-4-2021-1223",
        "kind": "image"
      },
      {
        "id": "media-t-cross-highline-1-4-2021-1223-02",
        "url": "/media/lotes/importados/t-cross-highline-1-4-2021-1223/02-tcross2.jpg",
        "alt": "Imagem 2 do lote t-cross-highline-1-4-2021-1223",
        "kind": "image"
      },
      {
        "id": "media-t-cross-highline-1-4-2021-1223-03",
        "url": "/media/lotes/importados/t-cross-highline-1-4-2021-1223/03-tcross3.jpg",
        "alt": "Imagem 3 do lote t-cross-highline-1-4-2021-1223",
        "kind": "image"
      },
      {
        "id": "media-t-cross-highline-1-4-2021-1223-04",
        "url": "/media/lotes/importados/t-cross-highline-1-4-2021-1223/04-tcross4.jpg",
        "alt": "Imagem 4 do lote t-cross-highline-1-4-2021-1223",
        "kind": "image"
      },
      {
        "id": "media-t-cross-highline-1-4-2021-1223-05",
        "url": "/media/lotes/importados/t-cross-highline-1-4-2021-1223/05-tcross5.jpg",
        "alt": "Imagem 5 do lote t-cross-highline-1-4-2021-1223",
        "kind": "image"
      },
      {
        "id": "media-t-cross-highline-1-4-2021-1223-06",
        "url": "/media/lotes/importados/t-cross-highline-1-4-2021-1223/06-tcross6.jpg",
        "alt": "Imagem 6 do lote t-cross-highline-1-4-2021-1223",
        "kind": "image"
      },
      {
        "id": "media-t-cross-highline-1-4-2021-1223-07",
        "url": "/media/lotes/importados/t-cross-highline-1-4-2021-1223/07-tcross7.webp",
        "alt": "Imagem 7 do lote t-cross-highline-1-4-2021-1223",
        "kind": "image"
      },
      {
        "id": "media-t-cross-highline-1-4-2021-1223-08",
        "url": "/media/lotes/importados/t-cross-highline-1-4-2021-1223/08-tcross8.jpg",
        "alt": "Imagem 8 do lote t-cross-highline-1-4-2021-1223",
        "kind": "image"
      },
      {
        "id": "media-t-cross-highline-1-4-2021-1223-09",
        "url": "/media/lotes/importados/t-cross-highline-1-4-2021-1223/09-tcross9.jpg",
        "alt": "Imagem 9 do lote t-cross-highline-1-4-2021-1223",
        "kind": "image"
      },
      {
        "id": "media-t-cross-highline-1-4-2021-1223-10",
        "url": "/media/lotes/importados/t-cross-highline-1-4-2021-1223/10-tcross10.jpg",
        "alt": "Imagem 10 do lote t-cross-highline-1-4-2021-1223",
        "kind": "image"
      },
      {
        "id": "media-t-cross-highline-1-4-2021-1223-11",
        "url": "/media/lotes/importados/t-cross-highline-1-4-2021-1223/11-tcross11.jpg",
        "alt": "Imagem 11 do lote t-cross-highline-1-4-2021-1223",
        "kind": "image"
      },
      {
        "id": "media-t-cross-highline-1-4-2021-1223-12",
        "url": "/media/lotes/importados/t-cross-highline-1-4-2021-1223/12-tcross12.jpg",
        "alt": "Imagem 12 do lote t-cross-highline-1-4-2021-1223",
        "kind": "image"
      },
      {
        "id": "media-t-cross-highline-1-4-2021-1223-13",
        "url": "/media/lotes/importados/t-cross-highline-1-4-2021-1223/13-tcross13.jpg",
        "alt": "Imagem 13 do lote t-cross-highline-1-4-2021-1223",
        "kind": "image"
      },
      {
        "id": "media-t-cross-highline-1-4-2021-1223-14",
        "url": "/media/lotes/importados/t-cross-highline-1-4-2021-1223/14-tcross14.jpg",
        "alt": "Imagem 14 do lote t-cross-highline-1-4-2021-1223",
        "kind": "image"
      }
    ],
    "documentIds": [],
    "faqIds": [],
    "technicalMetadata": {
      "yearModel": "2021",
      "usageMetric": "17.000 km",
      "fuel": "Flex"
    },
    "observations": {
      "sourceNote": "Importado do site antigo Kron Leilões em https://kronbergveiculos.github.io/LEIL-O/.",
      "commercialDisclaimer": "Dados, valores, disponibilidade, edital, comissão, pagamento, visitação e retirada devem ser confirmados com a equipe antes de qualquer decisão.",
      "operationalNotes": [
        "Marca: Volkswagem",
        "Modelo: Highline 1.4 TSI",
        "Ano: 2021",
        "Chaves: Com chave",
        "Quilometragem: 17.000 km",
        "Localização: Rua Cândido de Abreu – Curitiba/PR",
        "Lance inicial importado: R$ 15.000,00.",
        "Lance atual histórico no site antigo: R$ 16.410,00.",
        "Lance mínimo informado no site antigo: R$ 15.000,00."
      ]
    },
    "highlightBullets": [
      "Imagens baixadas do site antigo e servidas localmente pelo projeto.",
      "Referência fixa importada do lance inicial: R$ 15.000,00.",
      "Condições oficiais seguem dependentes de edital e atendimento."
    ],
    "ctaIds": [],
    "tags": [
      "veiculo",
      "importado-site-antigo"
    ],
    "seo": {
      "title": "T-cross Highline 1.4 2021",
      "description": "Lote #1223 importado do site antigo com imagens locais e referência fixa.",
      "canonicalPath": "/lotes/t-cross-highline-1-4-2021-1223",
      "keywords": [
        "veiculo",
        "importado-site-antigo"
      ],
      "ogImage": "/media/lotes/importados/t-cross-highline-1-4-2021-1223/01-tcross.webp"
    }
  },
  {
    "id": "old-site-lote-1002",
    "slug": "fiat-palio-2005-1002",
    "title": "Fiat Palio 2005",
    "subtitle": "Lote #1002 importado do site antigo com imagens locais e referência fixa.",
    "referenceCode": "Lote #1002",
    "eventId": "event-veiculos-premium",
    "categoryId": "category-veiculos-leves",
    "segmentLabel": "Veículo leve",
    "location": {
      "city": "Valinhos",
      "state": "SP",
      "display": "Valinhos/SP"
    },
    "statusKey": "sob-consulta",
    "statusLabel": "Sob consulta",
    "shortDescription": "Veículo em bom estado de funcionamento, bom de andar. Confirme edital, disponibilidade, documentação, pagamento e retirada com a equipe antes de avançar.",
    "longDescription": [
      "Fiat Palio 2005",
      "Veículo em bom estado de funcionamento, bom de andar.",
      "O lance inicial do site antigo foi usado como referência fixa do lote. O lance atual histórico foi mantido apenas como observação de origem, sem virar pré-lance no sistema atual."
    ],
    "gallery": [
      {
        "id": "media-fiat-palio-2005-1002-01",
        "url": "/media/lotes/importados/fiat-palio-2005-1002/01-palio2019.png",
        "alt": "Imagem 1 do lote fiat-palio-2005-1002",
        "kind": "image"
      }
    ],
    "documentIds": [],
    "faqIds": [],
    "technicalMetadata": {
      "yearModel": "2005",
      "usageMetric": "Não informada",
      "fuel": "Não informado"
    },
    "observations": {
      "sourceNote": "Importado do site antigo Kron Leilões em https://kronbergveiculos.github.io/LEIL-O/.",
      "commercialDisclaimer": "Dados, valores, disponibilidade, edital, comissão, pagamento, visitação e retirada devem ser confirmados com a equipe antes de qualquer decisão.",
      "operationalNotes": [
        "Parte mecânica revisada (óleo, batentes, homocinética, entre outros)",
        "IPVA: Pago",
        "Chave canivete",
        "Direção",
        "Trava elétrica",
        "Lance inicial importado: R$ 3.000,00.",
        "Lance atual histórico no site antigo: R$ 5.600,00.",
        "Lance mínimo informado no site antigo: R$ 4.000,00."
      ]
    },
    "highlightBullets": [
      "Imagens baixadas do site antigo e servidas localmente pelo projeto.",
      "Referência fixa importada do lance inicial: R$ 3.000,00.",
      "Condições oficiais seguem dependentes de edital e atendimento."
    ],
    "ctaIds": [],
    "tags": [
      "veiculo",
      "importado-site-antigo"
    ],
    "seo": {
      "title": "Fiat Palio 2005",
      "description": "Lote #1002 importado do site antigo com imagens locais e referência fixa.",
      "canonicalPath": "/lotes/fiat-palio-2005-1002",
      "keywords": [
        "veiculo",
        "importado-site-antigo"
      ],
      "ogImage": "/media/lotes/importados/fiat-palio-2005-1002/01-palio2019.png"
    }
  },
  {
    "id": "old-site-lote-1003",
    "slug": "fiat-palio-1003",
    "title": "Fiat Palio",
    "subtitle": "Lote #1003 importado do site antigo com imagens locais e referência fixa.",
    "referenceCode": "Lote #1003",
    "eventId": "event-veiculos-premium",
    "categoryId": "category-veiculos-leves",
    "segmentLabel": "Veículo leve",
    "location": {
      "city": "Curitiba",
      "state": "PR",
      "display": "Curitiba/PR"
    },
    "statusKey": "sob-consulta",
    "statusLabel": "Sob consulta",
    "shortDescription": "Veículo vendido no estado em que se encontra, destinado a circulação. Confirme edital, disponibilidade, documentação, pagamento e retirada com a equipe antes de avançar.",
    "longDescription": [
      "Fiat Palio",
      "Veículo vendido no estado em que se encontra, destinado a circulação.",
      "O lance inicial do site antigo foi usado como referência fixa do lote. O lance atual histórico foi mantido apenas como observação de origem, sem virar pré-lance no sistema atual."
    ],
    "gallery": [
      {
        "id": "media-fiat-palio-1003-01",
        "url": "/media/lotes/importados/fiat-palio-1003/01-palio4300.png",
        "alt": "Imagem 1 do lote fiat-palio-1003",
        "kind": "image"
      }
    ],
    "documentIds": [],
    "faqIds": [],
    "technicalMetadata": {
      "yearModel": "Não informado",
      "usageMetric": "Não informada",
      "fuel": "Não informado"
    },
    "observations": {
      "sourceNote": "Importado do site antigo Kron Leilões em https://kronbergveiculos.github.io/LEIL-O/.",
      "commercialDisclaimer": "Dados, valores, disponibilidade, edital, comissão, pagamento, visitação e retirada devem ser confirmados com a equipe antes de qualquer decisão.",
      "operationalNotes": [
        "Documento (DUT): Em mãos",
        "Documentação: Aproximadamente R$ 3.000",
        "IPVA: Pago",
        "Mecânica em bom funcionamento",
        "Motor em bom estado",
        "Suspensão em boas condições",
        "Pneus em bom estado",
        "Parte elétrica funcionando",
        "Marcador de combustível funcionando",
        "Veículo bateu e pegou",
        "Detalhe: Necessita reposição do vidro traseiro",
        "Lance inicial importado: R$ 5.500,00.",
        "Lance atual histórico no site antigo: R$ 4.750,00.",
        "Lance mínimo informado no site antigo: R$ 2.000,00."
      ]
    },
    "highlightBullets": [
      "Imagens baixadas do site antigo e servidas localmente pelo projeto.",
      "Referência fixa importada do lance inicial: R$ 5.500,00.",
      "Condições oficiais seguem dependentes de edital e atendimento."
    ],
    "ctaIds": [],
    "tags": [
      "veiculo",
      "importado-site-antigo"
    ],
    "seo": {
      "title": "Fiat Palio",
      "description": "Lote #1003 importado do site antigo com imagens locais e referência fixa.",
      "canonicalPath": "/lotes/fiat-palio-1003",
      "keywords": [
        "veiculo",
        "importado-site-antigo"
      ],
      "ogImage": "/media/lotes/importados/fiat-palio-1003/01-palio4300.png"
    }
  },
  {
    "id": "old-site-lote-1004",
    "slug": "chevrolet-corsa-1004",
    "title": "Chevrolet Corsa",
    "subtitle": "Lote #1004 importado do site antigo com imagens locais e referência fixa.",
    "referenceCode": "Lote #1004",
    "eventId": "event-veiculos-premium",
    "categoryId": "category-veiculos-leves",
    "segmentLabel": "Veículo leve",
    "location": {
      "city": "Porto Alegre",
      "state": "RS",
      "display": "Porto Alegre/RS"
    },
    "statusKey": "sob-consulta",
    "statusLabel": "Sob consulta",
    "shortDescription": "Chevrolet Corsa Sedan Classic Life 1.0 Flexpower Confirme edital, disponibilidade, documentação, pagamento e retirada com a equipe antes de avançar.",
    "longDescription": [
      "Chevrolet Corsa Sedan Classic Life 1.0 Flexpower",
      "O lance inicial do site antigo foi usado como referência fixa do lote. O lance atual histórico foi mantido apenas como observação de origem, sem virar pré-lance no sistema atual."
    ],
    "gallery": [
      {
        "id": "media-chevrolet-corsa-1004-01",
        "url": "/media/lotes/importados/chevrolet-corsa-1004/01-chovelet1.png",
        "alt": "Imagem 1 do lote chevrolet-corsa-1004",
        "kind": "image"
      },
      {
        "id": "media-chevrolet-corsa-1004-02",
        "url": "/media/lotes/importados/chevrolet-corsa-1004/02-chovelet2.png",
        "alt": "Imagem 2 do lote chevrolet-corsa-1004",
        "kind": "image"
      },
      {
        "id": "media-chevrolet-corsa-1004-03",
        "url": "/media/lotes/importados/chevrolet-corsa-1004/03-chevelet3.png",
        "alt": "Imagem 3 do lote chevrolet-corsa-1004",
        "kind": "image"
      }
    ],
    "documentIds": [],
    "faqIds": [],
    "technicalMetadata": {
      "yearModel": "2009",
      "usageMetric": "120.000 km",
      "fuel": "Álcool",
      "transmission": "Manual"
    },
    "observations": {
      "sourceNote": "Importado do site antigo Kron Leilões em https://kronbergveiculos.github.io/LEIL-O/.",
      "commercialDisclaimer": "Dados, valores, disponibilidade, edital, comissão, pagamento, visitação e retirada devem ser confirmados com a equipe antes de qualquer decisão.",
      "operationalNotes": [
        "Marca: Chevrolet",
        "Modelo: Corsa Sedan Classic Life 1.0 Flexpower",
        "Ano: 2009",
        "Quilometragem: 120.000 km",
        "Motor: 1.0",
        "Combustível: Álcool",
        "Câmbio: Manual",
        "IPVA: Pago",
        "Lance inicial importado: R$ 4.000,00.",
        "Lance atual histórico no site antigo: R$ 4.000,00.",
        "Lance mínimo informado no site antigo: R$ 2.000,00."
      ]
    },
    "highlightBullets": [
      "Imagens baixadas do site antigo e servidas localmente pelo projeto.",
      "Referência fixa importada do lance inicial: R$ 4.000,00.",
      "Condições oficiais seguem dependentes de edital e atendimento."
    ],
    "ctaIds": [],
    "tags": [
      "veiculo",
      "importado-site-antigo"
    ],
    "seo": {
      "title": "Chevrolet Corsa",
      "description": "Lote #1004 importado do site antigo com imagens locais e referência fixa.",
      "canonicalPath": "/lotes/chevrolet-corsa-1004",
      "keywords": [
        "veiculo",
        "importado-site-antigo"
      ],
      "ogImage": "/media/lotes/importados/chevrolet-corsa-1004/01-chovelet1.png"
    }
  },
  {
    "id": "old-site-lote-1005",
    "slug": "caminhonete-f350-1005",
    "title": "Caminhonete F350",
    "subtitle": "Lote #1005 importado do site antigo com imagens locais e referência fixa.",
    "referenceCode": "Lote #1005",
    "eventId": "event-operacao-frotas",
    "categoryId": "category-pickups-utilitarios",
    "segmentLabel": "Pick-up ou utilitário",
    "location": {
      "city": "Florianópolis",
      "state": "SC",
      "display": "Florianópolis/SC"
    },
    "statusKey": "sob-consulta",
    "statusLabel": "Sob consulta",
    "shortDescription": "Veículo vendido no estado em que se encontra. Confirme edital, disponibilidade, documentação, pagamento e retirada com a equipe antes de avançar.",
    "longDescription": [
      "Caminhonete F350",
      "Veículo vendido no estado em que se encontra.",
      "O lance inicial do site antigo foi usado como referência fixa do lote. O lance atual histórico foi mantido apenas como observação de origem, sem virar pré-lance no sistema atual."
    ],
    "gallery": [
      {
        "id": "media-caminhonete-f350-1005-01",
        "url": "/media/lotes/importados/caminhonete-f350-1005/01-camionet.png",
        "alt": "Imagem 1 do lote caminhonete-f350-1005",
        "kind": "image"
      },
      {
        "id": "media-caminhonete-f350-1005-02",
        "url": "/media/lotes/importados/caminhonete-f350-1005/02-camionet3.png",
        "alt": "Imagem 2 do lote caminhonete-f350-1005",
        "kind": "image"
      },
      {
        "id": "media-caminhonete-f350-1005-03",
        "url": "/media/lotes/importados/caminhonete-f350-1005/03-camionet4.png",
        "alt": "Imagem 3 do lote caminhonete-f350-1005",
        "kind": "image"
      },
      {
        "id": "media-caminhonete-f350-1005-04",
        "url": "/media/lotes/importados/caminhonete-f350-1005/04-camionet5.png",
        "alt": "Imagem 4 do lote caminhonete-f350-1005",
        "kind": "image"
      },
      {
        "id": "media-caminhonete-f350-1005-05",
        "url": "/media/lotes/importados/caminhonete-f350-1005/05-camionet6.png",
        "alt": "Imagem 5 do lote caminhonete-f350-1005",
        "kind": "image"
      },
      {
        "id": "media-caminhonete-f350-1005-06",
        "url": "/media/lotes/importados/caminhonete-f350-1005/06-camionet7.png",
        "alt": "Imagem 6 do lote caminhonete-f350-1005",
        "kind": "image"
      }
    ],
    "documentIds": [],
    "faqIds": [],
    "technicalMetadata": {
      "yearModel": "2001",
      "usageMetric": "Não informada",
      "fuel": "Diesel",
      "transmission": "Manual"
    },
    "observations": {
      "sourceNote": "Importado do site antigo Kron Leilões em https://kronbergveiculos.github.io/LEIL-O/.",
      "commercialDisclaimer": "Dados, valores, disponibilidade, edital, comissão, pagamento, visitação e retirada devem ser confirmados com a equipe antes de qualquer decisão.",
      "operationalNotes": [
        "Ano: 2001",
        "Combustível: Diesel",
        "Câmbio: Manual",
        "Direção: Hidráulica",
        "Quilometragem: Não informada",
        "Documentação e regularização: Não informada",
        "Lance inicial importado: R$ 10.000,00.",
        "Lance atual histórico no site antigo: R$ 10.280,00.",
        "Lance mínimo informado no site antigo: R$ 8.000,00."
      ]
    },
    "highlightBullets": [
      "Imagens baixadas do site antigo e servidas localmente pelo projeto.",
      "Referência fixa importada do lance inicial: R$ 10.000,00.",
      "Condições oficiais seguem dependentes de edital e atendimento."
    ],
    "ctaIds": [],
    "tags": [
      "pickup",
      "utilitario",
      "importado-site-antigo"
    ],
    "seo": {
      "title": "Caminhonete F350",
      "description": "Lote #1005 importado do site antigo com imagens locais e referência fixa.",
      "canonicalPath": "/lotes/caminhonete-f350-1005",
      "keywords": [
        "pickup",
        "utilitario",
        "importado-site-antigo"
      ],
      "ogImage": "/media/lotes/importados/caminhonete-f350-1005/01-camionet.png"
    }
  },
  {
    "id": "old-site-lote-1006",
    "slug": "fiat-uno-vivace-1006",
    "title": "Fiat Uno Vivace",
    "subtitle": "Lote #1006 importado do site antigo com imagens locais e referência fixa.",
    "referenceCode": "Lote #1006",
    "eventId": "event-veiculos-premium",
    "categoryId": "category-veiculos-leves",
    "segmentLabel": "Veículo leve",
    "location": {
      "city": "São Paulo",
      "state": "SP",
      "display": "São Paulo/SP"
    },
    "statusKey": "sob-consulta",
    "statusLabel": "Sob consulta",
    "shortDescription": "Veículo vendido no estado em que se encontra. Confirme edital, disponibilidade, documentação, pagamento e retirada com a equipe antes de avançar.",
    "longDescription": [
      "Fiat Uno Vivace/Rua 1.0 Evo Fire Flex 8V 5P",
      "Veículo vendido no estado em que se encontra.",
      "O lance inicial do site antigo foi usado como referência fixa do lote. O lance atual histórico foi mantido apenas como observação de origem, sem virar pré-lance no sistema atual."
    ],
    "gallery": [
      {
        "id": "media-fiat-uno-vivace-1006-01",
        "url": "/media/lotes/importados/fiat-uno-vivace-1006/01-fiat.png",
        "alt": "Imagem 1 do lote fiat-uno-vivace-1006",
        "kind": "image"
      },
      {
        "id": "media-fiat-uno-vivace-1006-02",
        "url": "/media/lotes/importados/fiat-uno-vivace-1006/02-fiat2.png",
        "alt": "Imagem 2 do lote fiat-uno-vivace-1006",
        "kind": "image"
      },
      {
        "id": "media-fiat-uno-vivace-1006-03",
        "url": "/media/lotes/importados/fiat-uno-vivace-1006/03-fiat3.png",
        "alt": "Imagem 3 do lote fiat-uno-vivace-1006",
        "kind": "image"
      },
      {
        "id": "media-fiat-uno-vivace-1006-04",
        "url": "/media/lotes/importados/fiat-uno-vivace-1006/04-fiat4.png",
        "alt": "Imagem 4 do lote fiat-uno-vivace-1006",
        "kind": "image"
      },
      {
        "id": "media-fiat-uno-vivace-1006-05",
        "url": "/media/lotes/importados/fiat-uno-vivace-1006/05-fiat5.png",
        "alt": "Imagem 5 do lote fiat-uno-vivace-1006",
        "kind": "image"
      },
      {
        "id": "media-fiat-uno-vivace-1006-06",
        "url": "/media/lotes/importados/fiat-uno-vivace-1006/06-fiat6.png",
        "alt": "Imagem 6 do lote fiat-uno-vivace-1006",
        "kind": "image"
      },
      {
        "id": "media-fiat-uno-vivace-1006-07",
        "url": "/media/lotes/importados/fiat-uno-vivace-1006/07-fiat7.png",
        "alt": "Imagem 7 do lote fiat-uno-vivace-1006",
        "kind": "image"
      }
    ],
    "documentIds": [],
    "faqIds": [],
    "technicalMetadata": {
      "yearModel": "2014",
      "usageMetric": "137.000 km",
      "fuel": "Flex"
    },
    "observations": {
      "sourceNote": "Importado do site antigo Kron Leilões em https://kronbergveiculos.github.io/LEIL-O/.",
      "commercialDisclaimer": "Dados, valores, disponibilidade, edital, comissão, pagamento, visitação e retirada devem ser confirmados com a equipe antes de qualquer decisão.",
      "operationalNotes": [
        "Marca: Fiat",
        "Tipo de veículo: Hatch",
        "Ano: 2014",
        "Quilometragem: 137.000 km",
        "Motor: 1.0",
        "Combustível: Flex",
        "Lance inicial importado: R$ 6.000,00.",
        "Lance atual histórico no site antigo: R$ 14.900,00.",
        "Lance mínimo informado no site antigo: R$ 10.000,00."
      ]
    },
    "highlightBullets": [
      "Imagens baixadas do site antigo e servidas localmente pelo projeto.",
      "Referência fixa importada do lance inicial: R$ 6.000,00.",
      "Condições oficiais seguem dependentes de edital e atendimento."
    ],
    "ctaIds": [],
    "tags": [
      "veiculo",
      "importado-site-antigo"
    ],
    "seo": {
      "title": "Fiat Uno Vivace",
      "description": "Lote #1006 importado do site antigo com imagens locais e referência fixa.",
      "canonicalPath": "/lotes/fiat-uno-vivace-1006",
      "keywords": [
        "veiculo",
        "importado-site-antigo"
      ],
      "ogImage": "/media/lotes/importados/fiat-uno-vivace-1006/01-fiat.png"
    }
  },
  {
    "id": "old-site-lote-1009",
    "slug": "volkswagen-gol-1-0-1009",
    "title": "Volkswagen Gol 1.0",
    "subtitle": "Lote #1009 importado do site antigo com imagens locais e referência fixa.",
    "referenceCode": "Lote #1009",
    "eventId": "event-veiculos-premium",
    "categoryId": "category-veiculos-leves",
    "segmentLabel": "Veículo leve",
    "location": {
      "city": "Rio de Janeiro",
      "state": "RJ",
      "display": "Rio de Janeiro/RJ"
    },
    "statusKey": "sob-consulta",
    "statusLabel": "Sob consulta",
    "shortDescription": "Veículo leiloado no estado em que se encontra. Confirme edital, disponibilidade, documentação, pagamento e retirada com a equipe antes de avançar.",
    "longDescription": [
      "Volkswagen Gol Geração IV Trend 1.0 8V MI Total Flex Mec. 2P",
      "Veículo leiloado no estado em que se encontra.",
      "O lance inicial do site antigo foi usado como referência fixa do lote. O lance atual histórico foi mantido apenas como observação de origem, sem virar pré-lance no sistema atual."
    ],
    "gallery": [
      {
        "id": "media-volkswagen-gol-1-0-1009-01",
        "url": "/media/lotes/importados/volkswagen-gol-1-0-1009/01-gol.png",
        "alt": "Imagem 1 do lote volkswagen-gol-1-0-1009",
        "kind": "image"
      },
      {
        "id": "media-volkswagen-gol-1-0-1009-02",
        "url": "/media/lotes/importados/volkswagen-gol-1-0-1009/02-gol2.png",
        "alt": "Imagem 2 do lote volkswagen-gol-1-0-1009",
        "kind": "image"
      },
      {
        "id": "media-volkswagen-gol-1-0-1009-03",
        "url": "/media/lotes/importados/volkswagen-gol-1-0-1009/03-gol3.png",
        "alt": "Imagem 3 do lote volkswagen-gol-1-0-1009",
        "kind": "image"
      },
      {
        "id": "media-volkswagen-gol-1-0-1009-04",
        "url": "/media/lotes/importados/volkswagen-gol-1-0-1009/04-gol4.png",
        "alt": "Imagem 4 do lote volkswagen-gol-1-0-1009",
        "kind": "image"
      },
      {
        "id": "media-volkswagen-gol-1-0-1009-05",
        "url": "/media/lotes/importados/volkswagen-gol-1-0-1009/05-gol5.png",
        "alt": "Imagem 5 do lote volkswagen-gol-1-0-1009",
        "kind": "image"
      },
      {
        "id": "media-volkswagen-gol-1-0-1009-06",
        "url": "/media/lotes/importados/volkswagen-gol-1-0-1009/06-gol6.png",
        "alt": "Imagem 6 do lote volkswagen-gol-1-0-1009",
        "kind": "image"
      },
      {
        "id": "media-volkswagen-gol-1-0-1009-07",
        "url": "/media/lotes/importados/volkswagen-gol-1-0-1009/07-gol7.png",
        "alt": "Imagem 7 do lote volkswagen-gol-1-0-1009",
        "kind": "image"
      },
      {
        "id": "media-volkswagen-gol-1-0-1009-08",
        "url": "/media/lotes/importados/volkswagen-gol-1-0-1009/08-gol8.png",
        "alt": "Imagem 8 do lote volkswagen-gol-1-0-1009",
        "kind": "image"
      },
      {
        "id": "media-volkswagen-gol-1-0-1009-09",
        "url": "/media/lotes/importados/volkswagen-gol-1-0-1009/09-gol9.png",
        "alt": "Imagem 9 do lote volkswagen-gol-1-0-1009",
        "kind": "image"
      },
      {
        "id": "media-volkswagen-gol-1-0-1009-10",
        "url": "/media/lotes/importados/volkswagen-gol-1-0-1009/10-gol10.png",
        "alt": "Imagem 10 do lote volkswagen-gol-1-0-1009",
        "kind": "image"
      },
      {
        "id": "media-volkswagen-gol-1-0-1009-11",
        "url": "/media/lotes/importados/volkswagen-gol-1-0-1009/11-gol11.png",
        "alt": "Imagem 11 do lote volkswagen-gol-1-0-1009",
        "kind": "image"
      }
    ],
    "documentIds": [],
    "faqIds": [],
    "technicalMetadata": {
      "yearModel": "2011",
      "usageMetric": "161.000 km",
      "fuel": "Flex",
      "transmission": "Manual"
    },
    "observations": {
      "sourceNote": "Importado do site antigo Kron Leilões em https://kronbergveiculos.github.io/LEIL-O/.",
      "commercialDisclaimer": "Dados, valores, disponibilidade, edital, comissão, pagamento, visitação e retirada devem ser confirmados com a equipe antes de qualquer decisão.",
      "operationalNotes": [
        "Marca: Volkswagen",
        "Tipo de veículo: Hatch",
        "Ano: 2011",
        "Quilometragem: 161.000 km",
        "Motor: 1.0",
        "Combustível: Flex",
        "Lance inicial importado: R$ 2.500,00.",
        "Lance atual histórico no site antigo: R$ 2.500,00.",
        "Lance mínimo informado no site antigo: R$ 1.000,00."
      ]
    },
    "highlightBullets": [
      "Imagens baixadas do site antigo e servidas localmente pelo projeto.",
      "Referência fixa importada do lance inicial: R$ 2.500,00.",
      "Condições oficiais seguem dependentes de edital e atendimento."
    ],
    "ctaIds": [],
    "tags": [
      "veiculo",
      "importado-site-antigo"
    ],
    "seo": {
      "title": "Volkswagen Gol 1.0",
      "description": "Lote #1009 importado do site antigo com imagens locais e referência fixa.",
      "canonicalPath": "/lotes/volkswagen-gol-1-0-1009",
      "keywords": [
        "veiculo",
        "importado-site-antigo"
      ],
      "ogImage": "/media/lotes/importados/volkswagen-gol-1-0-1009/01-gol.png"
    }
  },
  {
    "id": "old-site-lote-1010",
    "slug": "fiat-strada-working-1-4-1010",
    "title": "Fiat Strada Working 1.4",
    "subtitle": "Lote #1010 importado do site antigo com imagens locais e referência fixa.",
    "referenceCode": "Lote #1010",
    "eventId": "event-operacao-frotas",
    "categoryId": "category-pickups-utilitarios",
    "segmentLabel": "Pick-up ou utilitário",
    "location": {
      "city": "São Paulo",
      "state": "SP",
      "display": "São Paulo/SP"
    },
    "statusKey": "sob-consulta",
    "statusLabel": "Sob consulta",
    "shortDescription": "Veículo leiloado no estado em que se encontra. Confirme edital, disponibilidade, documentação, pagamento e retirada com a equipe antes de avançar.",
    "longDescription": [
      "Fiat Strada Working 1.4 MPI Fire Flex 8V CS",
      "Veículo leiloado no estado em que se encontra.",
      "O lance inicial do site antigo foi usado como referência fixa do lote. O lance atual histórico foi mantido apenas como observação de origem, sem virar pré-lance no sistema atual."
    ],
    "gallery": [
      {
        "id": "media-fiat-strada-working-1-4-1010-01",
        "url": "/media/lotes/importados/fiat-strada-working-1-4-1010/01-std.png",
        "alt": "Imagem 1 do lote fiat-strada-working-1-4-1010",
        "kind": "image"
      },
      {
        "id": "media-fiat-strada-working-1-4-1010-02",
        "url": "/media/lotes/importados/fiat-strada-working-1-4-1010/02-std2.png",
        "alt": "Imagem 2 do lote fiat-strada-working-1-4-1010",
        "kind": "image"
      },
      {
        "id": "media-fiat-strada-working-1-4-1010-03",
        "url": "/media/lotes/importados/fiat-strada-working-1-4-1010/03-std3.png",
        "alt": "Imagem 3 do lote fiat-strada-working-1-4-1010",
        "kind": "image"
      },
      {
        "id": "media-fiat-strada-working-1-4-1010-04",
        "url": "/media/lotes/importados/fiat-strada-working-1-4-1010/04-std4.png",
        "alt": "Imagem 4 do lote fiat-strada-working-1-4-1010",
        "kind": "image"
      },
      {
        "id": "media-fiat-strada-working-1-4-1010-05",
        "url": "/media/lotes/importados/fiat-strada-working-1-4-1010/05-std5.png",
        "alt": "Imagem 5 do lote fiat-strada-working-1-4-1010",
        "kind": "image"
      },
      {
        "id": "media-fiat-strada-working-1-4-1010-06",
        "url": "/media/lotes/importados/fiat-strada-working-1-4-1010/06-std6.png",
        "alt": "Imagem 6 do lote fiat-strada-working-1-4-1010",
        "kind": "image"
      },
      {
        "id": "media-fiat-strada-working-1-4-1010-07",
        "url": "/media/lotes/importados/fiat-strada-working-1-4-1010/07-std7.png",
        "alt": "Imagem 7 do lote fiat-strada-working-1-4-1010",
        "kind": "image"
      },
      {
        "id": "media-fiat-strada-working-1-4-1010-08",
        "url": "/media/lotes/importados/fiat-strada-working-1-4-1010/08-std8.png",
        "alt": "Imagem 8 do lote fiat-strada-working-1-4-1010",
        "kind": "image"
      },
      {
        "id": "media-fiat-strada-working-1-4-1010-09",
        "url": "/media/lotes/importados/fiat-strada-working-1-4-1010/09-std10.png",
        "alt": "Imagem 9 do lote fiat-strada-working-1-4-1010",
        "kind": "image"
      }
    ],
    "documentIds": [],
    "faqIds": [],
    "technicalMetadata": {
      "yearModel": "2016",
      "usageMetric": "128.000 km",
      "fuel": "Flex"
    },
    "observations": {
      "sourceNote": "Importado do site antigo Kron Leilões em https://kronbergveiculos.github.io/LEIL-O/.",
      "commercialDisclaimer": "Dados, valores, disponibilidade, edital, comissão, pagamento, visitação e retirada devem ser confirmados com a equipe antes de qualquer decisão.",
      "operationalNotes": [
        "Marca: Fiat",
        "Tipo de veículo: Pick-up",
        "Ano: 2016",
        "Quilometragem: 128.000 km",
        "Motor: 1.4",
        "Combustível: Flex",
        "Lance inicial importado: R$ 7.000,00.",
        "Lance atual histórico no site antigo: R$ 7.000,00.",
        "Lance mínimo informado no site antigo: R$ 1.000,00."
      ]
    },
    "highlightBullets": [
      "Imagens baixadas do site antigo e servidas localmente pelo projeto.",
      "Referência fixa importada do lance inicial: R$ 7.000,00.",
      "Condições oficiais seguem dependentes de edital e atendimento."
    ],
    "ctaIds": [],
    "tags": [
      "pickup",
      "utilitario",
      "importado-site-antigo"
    ],
    "seo": {
      "title": "Fiat Strada Working 1.4",
      "description": "Lote #1010 importado do site antigo com imagens locais e referência fixa.",
      "canonicalPath": "/lotes/fiat-strada-working-1-4-1010",
      "keywords": [
        "pickup",
        "utilitario",
        "importado-site-antigo"
      ],
      "ogImage": "/media/lotes/importados/fiat-strada-working-1-4-1010/01-std.png"
    }
  },
  {
    "id": "old-site-lote-1011",
    "slug": "hyundai-gls-1-8-1011",
    "title": "Hyundai GLS 1.8",
    "subtitle": "Lote #1011 importado do site antigo com imagens locais e referência fixa.",
    "referenceCode": "Lote #1011",
    "eventId": "event-veiculos-premium",
    "categoryId": "category-veiculos-leves",
    "segmentLabel": "Veículo leve",
    "location": {
      "city": "Belo Horizonte",
      "state": "MG",
      "display": "Belo Horizonte/MG"
    },
    "statusKey": "sob-consulta",
    "statusLabel": "Sob consulta",
    "shortDescription": "Veículo leiloado no estado em que se encontra. Confirme edital, disponibilidade, documentação, pagamento e retirada com a equipe antes de avançar.",
    "longDescription": [
      "Hyundai GLS 1.8 16V Automático",
      "Veículo leiloado no estado em que se encontra.",
      "O lance inicial do site antigo foi usado como referência fixa do lote. O lance atual histórico foi mantido apenas como observação de origem, sem virar pré-lance no sistema atual."
    ],
    "gallery": [
      {
        "id": "media-hyundai-gls-1-8-1011-01",
        "url": "/media/lotes/importados/hyundai-gls-1-8-1011/01-hudai.png",
        "alt": "Imagem 1 do lote hyundai-gls-1-8-1011",
        "kind": "image"
      },
      {
        "id": "media-hyundai-gls-1-8-1011-02",
        "url": "/media/lotes/importados/hyundai-gls-1-8-1011/02-hudai2.png",
        "alt": "Imagem 2 do lote hyundai-gls-1-8-1011",
        "kind": "image"
      },
      {
        "id": "media-hyundai-gls-1-8-1011-03",
        "url": "/media/lotes/importados/hyundai-gls-1-8-1011/03-hudai3.png",
        "alt": "Imagem 3 do lote hyundai-gls-1-8-1011",
        "kind": "image"
      },
      {
        "id": "media-hyundai-gls-1-8-1011-04",
        "url": "/media/lotes/importados/hyundai-gls-1-8-1011/04-hudai4.png",
        "alt": "Imagem 4 do lote hyundai-gls-1-8-1011",
        "kind": "image"
      },
      {
        "id": "media-hyundai-gls-1-8-1011-05",
        "url": "/media/lotes/importados/hyundai-gls-1-8-1011/05-hudai5.png",
        "alt": "Imagem 5 do lote hyundai-gls-1-8-1011",
        "kind": "image"
      }
    ],
    "documentIds": [],
    "faqIds": [],
    "technicalMetadata": {
      "yearModel": "2013",
      "usageMetric": "210.000 km",
      "fuel": "Gasolina",
      "transmission": "Automática"
    },
    "observations": {
      "sourceNote": "Importado do site antigo Kron Leilões em https://kronbergveiculos.github.io/LEIL-O/.",
      "commercialDisclaimer": "Dados, valores, disponibilidade, edital, comissão, pagamento, visitação e retirada devem ser confirmados com a equipe antes de qualquer decisão.",
      "operationalNotes": [
        "Marca: Hyundai",
        "Tipo de veículo: Sedã",
        "Ano: 2013",
        "Quilometragem: 210.000 km",
        "Motor: 1.8",
        "Combustível: Gasolina",
        "Lance inicial importado: R$ 4.500,00.",
        "Lance atual histórico no site antigo: R$ 4.500,00.",
        "Lance mínimo informado no site antigo: R$ 1.000,00."
      ]
    },
    "highlightBullets": [
      "Imagens baixadas do site antigo e servidas localmente pelo projeto.",
      "Referência fixa importada do lance inicial: R$ 4.500,00.",
      "Condições oficiais seguem dependentes de edital e atendimento."
    ],
    "ctaIds": [],
    "tags": [
      "veiculo",
      "importado-site-antigo"
    ],
    "seo": {
      "title": "Hyundai GLS 1.8",
      "description": "Lote #1011 importado do site antigo com imagens locais e referência fixa.",
      "canonicalPath": "/lotes/hyundai-gls-1-8-1011",
      "keywords": [
        "veiculo",
        "importado-site-antigo"
      ],
      "ogImage": "/media/lotes/importados/hyundai-gls-1-8-1011/01-hudai.png"
    }
  },
  {
    "id": "old-site-lote-1013",
    "slug": "honda-cg-titan-1013",
    "title": "Honda CG Titan",
    "subtitle": "Lote #1013 importado do site antigo com imagens locais e referência fixa.",
    "referenceCode": "Lote #1013",
    "eventId": "event-motos-maquinas",
    "categoryId": "category-motocicletas",
    "segmentLabel": "Motocicleta",
    "location": {
      "city": "Goiânia",
      "state": "GO",
      "display": "Goiânia/GO"
    },
    "statusKey": "sob-consulta",
    "statusLabel": "Sob consulta",
    "shortDescription": "Veículo leiloado no estado em que se encontra. Confirme edital, disponibilidade, documentação, pagamento e retirada com a equipe antes de avançar.",
    "longDescription": [
      "Honda CG 160 Titan FlexOne Edição Especial 40 Anos",
      "Veículo leiloado no estado em que se encontra.",
      "O lance inicial do site antigo foi usado como referência fixa do lote. O lance atual histórico foi mantido apenas como observação de origem, sem virar pré-lance no sistema atual."
    ],
    "gallery": [
      {
        "id": "media-honda-cg-titan-1013-01",
        "url": "/media/lotes/importados/honda-cg-titan-1013/01-honda.png",
        "alt": "Imagem 1 do lote honda-cg-titan-1013",
        "kind": "image"
      },
      {
        "id": "media-honda-cg-titan-1013-02",
        "url": "/media/lotes/importados/honda-cg-titan-1013/02-honda2.png",
        "alt": "Imagem 2 do lote honda-cg-titan-1013",
        "kind": "image"
      },
      {
        "id": "media-honda-cg-titan-1013-03",
        "url": "/media/lotes/importados/honda-cg-titan-1013/03-honda3.png",
        "alt": "Imagem 3 do lote honda-cg-titan-1013",
        "kind": "image"
      },
      {
        "id": "media-honda-cg-titan-1013-04",
        "url": "/media/lotes/importados/honda-cg-titan-1013/04-honda4.png",
        "alt": "Imagem 4 do lote honda-cg-titan-1013",
        "kind": "image"
      },
      {
        "id": "media-honda-cg-titan-1013-05",
        "url": "/media/lotes/importados/honda-cg-titan-1013/05-honda5.png",
        "alt": "Imagem 5 do lote honda-cg-titan-1013",
        "kind": "image"
      },
      {
        "id": "media-honda-cg-titan-1013-06",
        "url": "/media/lotes/importados/honda-cg-titan-1013/06-honda6.png",
        "alt": "Imagem 6 do lote honda-cg-titan-1013",
        "kind": "image"
      },
      {
        "id": "media-honda-cg-titan-1013-07",
        "url": "/media/lotes/importados/honda-cg-titan-1013/07-honda7.png",
        "alt": "Imagem 7 do lote honda-cg-titan-1013",
        "kind": "image"
      }
    ],
    "documentIds": [],
    "faqIds": [],
    "technicalMetadata": {
      "yearModel": "2025",
      "usageMetric": "93 km",
      "fuel": "Flex"
    },
    "observations": {
      "sourceNote": "Importado do site antigo Kron Leilões em https://kronbergveiculos.github.io/LEIL-O/.",
      "commercialDisclaimer": "Dados, valores, disponibilidade, edital, comissão, pagamento, visitação e retirada devem ser confirmados com a equipe antes de qualquer decisão.",
      "operationalNotes": [
        "Marca: Honda",
        "Ano: 2025",
        "Quilometragem: 93 km",
        "Lance inicial importado: R$ 1.500,00.",
        "Lance atual histórico no site antigo: R$ 1.500,00.",
        "Lance mínimo informado no site antigo: R$ 1.000,00."
      ]
    },
    "highlightBullets": [
      "Imagens baixadas do site antigo e servidas localmente pelo projeto.",
      "Referência fixa importada do lance inicial: R$ 1.500,00.",
      "Condições oficiais seguem dependentes de edital e atendimento."
    ],
    "ctaIds": [],
    "tags": [
      "moto",
      "mobilidade",
      "importado-site-antigo"
    ],
    "seo": {
      "title": "Honda CG Titan",
      "description": "Lote #1013 importado do site antigo com imagens locais e referência fixa.",
      "canonicalPath": "/lotes/honda-cg-titan-1013",
      "keywords": [
        "moto",
        "mobilidade",
        "importado-site-antigo"
      ],
      "ogImage": "/media/lotes/importados/honda-cg-titan-1013/01-honda.png"
    }
  }
];

export const importedOldSiteEventLotIds = {
  "event-motos-maquinas": [
    "old-site-lote-1001",
    "old-site-lote-1013"
  ],
  "event-veiculos-premium": [
    "old-site-lote-1223",
    "old-site-lote-1002",
    "old-site-lote-1003",
    "old-site-lote-1004",
    "old-site-lote-1006",
    "old-site-lote-1009",
    "old-site-lote-1011"
  ],
  "event-operacao-frotas": [
    "old-site-lote-1005",
    "old-site-lote-1010"
  ]
};

export const importedOldSiteMarketBySlug = {
  "honda-biz-110i-2022-1001": {
    "referenceValueCents": 110000,
    "minimumIncrementCents": 10000,
    "onlineStatusLabel": "Consulta assistida",
    "teaserLabel": "Referência importada do site antigo",
    "supportLabel": "Lance inicial importado como referência fixa"
  },
  "t-cross-highline-1-4-2021-1223": {
    "referenceValueCents": 1500000,
    "minimumIncrementCents": 22000,
    "onlineStatusLabel": "Consulta assistida",
    "teaserLabel": "Referência importada do site antigo",
    "supportLabel": "Lance inicial importado como referência fixa"
  },
  "fiat-palio-2005-1002": {
    "referenceValueCents": 300000,
    "minimumIncrementCents": 50000,
    "onlineStatusLabel": "Consulta assistida",
    "teaserLabel": "Referência importada do site antigo",
    "supportLabel": "Lance inicial importado como referência fixa"
  },
  "fiat-palio-1003": {
    "referenceValueCents": 550000,
    "minimumIncrementCents": 50000,
    "onlineStatusLabel": "Consulta assistida",
    "teaserLabel": "Referência importada do site antigo",
    "supportLabel": "Lance inicial importado como referência fixa"
  },
  "chevrolet-corsa-1004": {
    "referenceValueCents": 400000,
    "minimumIncrementCents": 50000,
    "onlineStatusLabel": "Consulta assistida",
    "teaserLabel": "Referência importada do site antigo",
    "supportLabel": "Lance inicial importado como referência fixa"
  },
  "caminhonete-f350-1005": {
    "referenceValueCents": 1000000,
    "minimumIncrementCents": 50000,
    "onlineStatusLabel": "Consulta assistida",
    "teaserLabel": "Referência importada do site antigo",
    "supportLabel": "Lance inicial importado como referência fixa"
  },
  "fiat-uno-vivace-1006": {
    "referenceValueCents": 600000,
    "minimumIncrementCents": 50000,
    "onlineStatusLabel": "Consulta assistida",
    "teaserLabel": "Referência importada do site antigo",
    "supportLabel": "Lance inicial importado como referência fixa"
  },
  "volkswagen-gol-1-0-1009": {
    "referenceValueCents": 250000,
    "minimumIncrementCents": 50000,
    "onlineStatusLabel": "Consulta assistida",
    "teaserLabel": "Referência importada do site antigo",
    "supportLabel": "Lance inicial importado como referência fixa"
  },
  "fiat-strada-working-1-4-1010": {
    "referenceValueCents": 700000,
    "minimumIncrementCents": 50000,
    "onlineStatusLabel": "Consulta assistida",
    "teaserLabel": "Referência importada do site antigo",
    "supportLabel": "Lance inicial importado como referência fixa"
  },
  "hyundai-gls-1-8-1011": {
    "referenceValueCents": 450000,
    "minimumIncrementCents": 50000,
    "onlineStatusLabel": "Consulta assistida",
    "teaserLabel": "Referência importada do site antigo",
    "supportLabel": "Lance inicial importado como referência fixa"
  },
  "honda-cg-titan-1013": {
    "referenceValueCents": 150000,
    "minimumIncrementCents": 20000,
    "onlineStatusLabel": "Consulta assistida",
    "teaserLabel": "Referência importada do site antigo",
    "supportLabel": "Lance inicial importado como referência fixa"
  }
};
